# Generated by Django 3.2.8 on 2022-09-04 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_customuser_first_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='USERNAME_FIELD',
            field=models.CharField(default='username', max_length=10, unique=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='username',
            field=models.CharField(default='username', max_length=10, unique=True),
        ),
    ]
