# Generated by Django 3.2.8 on 2022-09-04 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_customuser_username_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='USERNAME_FIELD',
        ),
    ]
