# Generated by Django 3.2.8 on 2022-09-04 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_remove_customuser_username_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='username',
        ),
    ]
