# Generated by Django 3.2.8 on 2022-09-04 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_remove_customuser_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='username',
            field=models.CharField(default='abc', max_length=20),
            preserve_default=False,
        ),
    ]
