# Generated by Django 3.2.8 on 2022-09-04 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_alter_customuser_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='username',
        ),
    ]
