# Generated by Django 3.2.8 on 2022-01-18 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_id',
            field=models.CharField(default=123, max_length=250),
            preserve_default=False,
        ),
    ]
